# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 777adfb0752482281b9ee49425afa5c636d653fee5394266d74bec3eb6882abe9bd10e9f545c6f17a16ae6db4c2475db706ebd3a64e57aaeafca23b861b1363d

test:
  secret_key_base: 87834d9a65ee531dc9d058ac3795d8441426fc919807f5ee7709dfa786560fcf2b63836b52faa20a89d48ba2abe907df9d2ce83c821edf32e890ff6083c51541

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
